language: python
python:
  - "3.7"
cache: pip3
install:
  - pip3 install -r requirements.txt
services:
  - sqllite
before script:
  
script: 
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test